"""add index on urls.expires_at

Revision ID: 5bfcb79de489
Revises: f5c28243f95c
Create Date: 2026-10-01 22:57:38.591785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfcb79de489'
down_revision: Union[str, Sequence[str], None] = 'f5c28243f95c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_urls_expires_at'), 'urls', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_expires_at'), table_name='urls')
    # ### end Alembic commands ###
